batch_size: 100
max_retries: 3
workflows:
  daily:
    routine_name: daily
    description: "Structured daily routine for productivity, wellbeing, and focus. Designed to support neurodiverse needs including ADHD and autism."
    routine_file: "daily-routine.md"
    category: "focus, wellbeing, neurodiverse"
    repeat: daily
    active: true
    start_date: null  # Override via CLI or script
    end_date: null    # Computed using duration_days or overridden
    duration_days: null  # Override via CLI if needed
    watch: false
  urgent_rest:
    routine_name: urgent-rest
    description: "Recovery-oriented rest protocol for managing overwhelm, psychosis symptoms, or sensory overload. Adjusts work cadence to allow restorative time."
    routine_file: "rest-routine.md"
    category: "rest, recovery, neurodiverse support"
    repeat: daily
    active: false
    start_date: null  # Override via CLI or script
    end_date: null    # Computed using duration_days or overridden
    duration_days: null  # Override via CLI if needed
    watch: false
  complete:
    routine_name: complete
    description: "Recovery-oriented rest protocol for managing overwhelm, psychosis symptoms, or sensory overload. Adjusts work cadence to allow restorative time."
    routine_file: "rest-routine.md"
    category: "rest, recovery, neurodiverse support"
    repeat: daily
    active: false
    start_date: null        # Override via CLI or script (format: YYYY-MM-DD)
    end_date: null          # Computed automatically from start_date + duration_days unless overridden
    duration_days: 7        # Default duration (days), can be overridden via CLI
    watch: false
